apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 8080
  selector:
    app: frontend
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend:latest
        name: frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: port
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        ports:
        - containerPort: 8080