kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingress-secret-admin
rules:
- apiGroups: [""]
  resources: ["secrets", "endpoints"]
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
- apiGroups: [""]
  resources: ["services"]
  verbs:
  - get
  - create
  - delete
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-lego
roleRef:
  kind: ClusterRole
  name: ingress-secret-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-lego