apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-proxy
    spec:
      containers:
        - image: gcr.io/cloudsql-docker/gce-proxy:1.11
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=hourinetwork:europe-west1:mysql=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-proxy
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-proxy
  type: NodePort